#pragma once
#define DEPTH_STENCIL_FORMAT DXGI_FORMAT_D24_UNORM_S8_UINT
#define SWAP_CHAIN_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM
#define SWAP_BUFFER_COUNT 2
#define NUMBER_OF_THREADS 4
#define MAIN_THREAD NUMBER_OF_THREADS - 1
#define THREAD_ID 0
#define WWidth 100
#define HHeight 100
#define LOADINGTHRESHOLD 3